# Generated by Django 6.0.6 on 2026-06-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("EC", "Economics"),
                            ("LW", "Law"),
                            ("PH", "Public Health"),
                        ],
                        max_length=100,
                    ),
                ),
                ("supervisor", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("thesis", "Thesis"),
                            ("dissertation", "Dissertation"),
                            ("research_paper", "Research Paper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=500
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, upload_to="papers/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "institution",
                    models.CharField(default="Scholar Corridor", max_length=200),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
